# Generated by Django 4.0.6 on 2023-07-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(db_column='name', max_length=255)),
                ('age', models.IntegerField(db_column='age')),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('roll_number', models.AutoField(db_column='roll_number', primary_key=True, serialize=False)),
                ('created_timestam', models.DateTimeField(db_column='created_timestamp')),
            ],
            options={
                'db_table': 'Master"."studnet',
                'managed': False,
            },
        ),
    ]
